FutebolLimaDuarte/GerenciadorCampeonato/Models/EnviarMensagemGoogle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GerenciadorCampeonato.Models
{
    public class EnviarMensagemGoogle
    {
        public String Message { get; set; }

        public String TickerText { get; set; }

        public String ContentTitle { get; set; }
    }
}

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Controllers/CampeonatoController.cs
using Campeonato.Aplicacao;
using Campeonato.Dominio;
using Campeonato.Aplicacao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Campeonato.UI.WEB.Security;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Text;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;

namespace Campeonato.UI.WEB.Areas.Admin
{
    public class CampeonatoController : Controller
    {
        //
        // GET: /Admin/Campeonato/

        private readonly CampeonatoAplicacao appCampeonato;
        private readonly TimeAplicacao appTimes;
        private readonly NoticiaAplicacao appNoticia;

        private readonly ClassificacaoAplicacao appClassificacao;

        public CampeonatoController()
        {
            appCampeonato = CampeonatoAplicacaoConstrutor.CampeonatoAplicacaoADO();
            appClassificacao = ClassificacaoAplicacaoConstrutor.ClassificacaoAplicacaoADO();
            appNoticia = NoticiaAplicacaoConstrutor.NoticiaAplicacaoADO();
        }

        public ActionResult Index()
        {
            var listaDeCampeonatos = appCampeonato.ListarTodos();
            return View(listaDeCampeonatos);
        }

        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Cadastrar(Campeonatos campeonato)
        {
            if (ModelState.IsValid)
            {
                appCampeonato.Salvar(campeonato);
                return RedirectToAction("Index");
            }
            return View(campeonato);
        }


        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult SelecionarTimes(string id)
        {
            //var listaDeCampeonatos = appCampeonato.ListarTodos();
            TimeCampeonato timesCampeonato = new TimeCampeonato();
            timesCampeonato.Times = appTimes.ListarTodos();
            timesCampeonato.IdCampeonato = id;
            return View(timesCampeonato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult SelecionarTimes(int id)
        {

            var listaTimes = appTimes.ListarTodos();
            var listaTimesAdicionar = new List<Time>();

            for (int i = 0; i < listaTimes.Count(); i++)
            {
                Time time = listaTimes.ToList<Time>()[i];

                for (int j = 0; j < Request.Form.Count; j++)
                {
                    if (Request.Form.Keys[j].Equals(time.Id.ToString()))
                    {
                        var checkbox = Request.Form[j];
                        if (checkbox != "false")
                        {
                            time.SelecionadoCampeonato = true;
                            listaTimesAdicionar.Add(time);
                        }
                    }
                }
            }
            //Arrumar - JOAO CELSON

            appCampeonato.AdicionarTimes(listaTimesAdicionar, id.ToString());
            return RedirectToAction("TimesPorCampeonato");
        }

        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Editar(string id)
        {
            var campeonato = appCampeonato.ListarPorId(id);

            if (campeonato == null)
                return HttpNotFound();

            return View(campeonato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Editar(Campeonatos campeonato)
        {
            if (ModelState.IsValid)
            {
                appCampeonato.Salvar(campeonato);
                return RedirectToAction("Index");
            }
            return View(campeonato);
        }

        public ActionResult Detalhes(string id)
        {
            var campeonato = appCampeonato.ListarPorId(id);

            if (campeonato == null)
                return HttpNotFound();

            return View(campeonato);
        }

        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult Excluir(string id)
        {
            var campeonato = appCampeonato.ListarPorId(id);

            if (campeonato == null)
                return HttpNotFound();

            return View(campeonato);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        [PermissoesFiltro(Roles = "Admin")]
        public ActionResult ExcluirConfirmado(string id)
        {
            var campeonato = appCampeonato.ListarPorId(id);
            appCampeonato.Excluir(campeonato);
            return RedirectToAction("Index");
        }

        public ActionResult TimesPorCampeonato(string idCampeonato)
        {
            TimeCampeonato timeCampeonato = new TimeCampeonato();
            timeCampeonato.Times = appTimes.ListarTimesCampeonato(idCampeonato);
            timeCampeonato.IdCampeonato = idCampeonato;
            return View(timeCampeonato);
        }

        public ActionResult Tabela(string id)
        {
            return RedirectToAction("Tabela", new RouteValueDictionary(
    new { controller = "Partida", action = "Tabela", Id = id }));

        }

        public ActionResult Classificacao(string id)
        {
            var listaClassificacao = appClassificacao.ListarClassicacaoPorCampeonato(id);
            return View(listaClassificacao);
        }

        public ActionResult CampeoesPorCampeonato(string id)
        {
            var listaCampeos = appClassificacao.ListarCampeoesPorCampeonato(id);
            return View(listaCampeos);
        }

        public ActionResult EnviarMensagemGoogle()
        {
            return View();
        }


        //JSON - Retorna todos os dados JSON
        //=======================================================



        public String ObterClassificacaoJson(string id)
        {
            List<Classificacao> listaClassificacao = (List<Classificacao>)appClassificacao.ListarClassicacaoPorCampeonato(id);

            //if (id.Equals("3"))
            //{
            //    Classificacao classificacaoA = new Classificacao();
            //    classificacaoA.Posicao = "";
            //    classificacaoA.NomeTime = "GRUPO A";
            //    classificacaoA.Pontos = "";
            //    listaClassificacao.Insert(0, classificacaoA);

            //    List<Classificacao> listaClassificacaoB = (List<Classificacao>)appClassificacao.ListarClassicacaoPorCampeonato("4");
            //    Classificacao classificacao = new Classificacao();
            //    classificacao.Posicao = "";
            //    classificacao.NomeTime = "GRUPO B";
            //    classificacao.Pontos = "";
            //    listaClassificacao.Add(classificacao);
            //    foreach (Classificacao b in listaClassificacaoB)
            //    {
            //        listaClassificacao.Add(b);
            //    }

            //}
            Classificacao classificacao2 = new Classificacao();
            classificacao2.Posicao = " ";
            classificacao2.NomeTime = " ";
            classificacao2.Pontos = " ";
            listaClassificacao.Add(classificacao2);

            return JsonConvert.SerializeObject(listaClassificacao, Formatting.Indented);
        }

        public String ObterClassificacaoGeralJson()
        {
            List<Classificacao> listaClassificacao = (List<Classificacao>)appClassificacao.ListarClassicacaoGeral();

            //if (id.Equals("3"))
            //{
            //    Classificacao classificacaoA = new Classificacao();
            //    classificacaoA.Posicao = "";
            //    classificacaoA.NomeTime = "GRUPO A";
            //    classificacaoA.Pontos = "";
            //    listaClassificacao.Insert(0, classificacaoA);

            //    List<Classificacao> listaClassificacaoB = (List<Classificacao>)appClassificacao.ListarClassicacaoPorCampeonato("4");
            //    Classificacao classificacao = new Classificacao();
            //    classificacao.Posicao = "";
            //    classificacao.NomeTime = "GRUPO B";
            //    classificacao.Pontos = "";
            //    listaClassificacao.Add(classificacao);
            //    foreach (Classificacao b in listaClassificacaoB)
            //    {
            //        listaClassificacao.Add(b);
            //    }

            //}
            Classificacao classificacao2 = new Classificacao();
            classificacao2.Posicao = " ";
            classificacao2.NomeTime = " ";
            classificacao2.Pontos = " ";
            listaClassificacao.Add(classificacao2);

            return JsonConvert.SerializeObject(listaClassificacao, Formatting.Indented);
        }

        public String ObterArtilhariaJson(string id)
        {
            var listaArtilheiros = appCampeonato.ArtilhariaPorCampeonato(id);
            Artilheiro artilheiro = new Artilheiro();
            artilheiro.Nome = " ";
            artilheiro.NumeroGols = "0";
            artilheiro.Time = " ";
            List<Artilheiro> artilheiros =  listaArtilheiros.ToList<Artilheiro>();
            artilheiros.Add(artilheiro);
            return JsonConvert.SerializeObject(artilheiros, Formatting.Indented);
        }

        public String ObterArtilhariaGeralJson()
        {
            var listaArtilheiros = appCampeonato.ArtilhariaPorCampeonatoGeral();
            Artilheiro artilheiro = new Artilheiro();
            artilheiro.Nome = " ";
            artilheiro.NumeroGols = "0";
            artilheiro.Time = " ";
            List<Artilheiro> artilheiros = listaArtilheiros.ToList<Artilheiro>();
            artilheiros.Add(artilheiro);
            return JsonConvert.SerializeObject(artilheiros, Formatting.Indented);
        }

        public String Noticias()
        {

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/Cadastrar.cshtml
@model Campeonato.Dominio.Campeonatos

@{
    ViewBag.Title = "Futebol Lima Duarte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <h2>Cadastrar</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Campeonatos</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Nome)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nome)
                @Html.ValidationMessageFor(model => model.Nome)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.DataInicio)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DataInicio)
                @Html.ValidationMessageFor(model => model.DataInicio)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.QuantidadeTime)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.QuantidadeTime)
                @Html.ValidationMessageFor(model => model.QuantidadeTime)
            </div>

            <p>
                <input class="btn btn-primary btn-large" type="submit" value="Cadastrar" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>

</div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/CampeoesPorCampeonato.cshtml
@model IEnumerable<Campeonato.Dominio.Campeoes>

    @{
        ViewBag.Title = "Futebol Lima Duarte";
        Layout = "~/Views/Shared/_Layout.cshtml";
        List<Campeonato.Dominio.Campeoes> listaCampeoes = new List<Campeonato.Dominio.Campeoes>();
    }
    <h2>Campeões geral</h2>
    @foreach (var item in Model)
    {
        if (listaCampeoes.Count == 0)
        {
            listaCampeoes.Add(item);
        }
        else
        {
            bool inserir = false;
            for (int i = 0; i < listaCampeoes.Count; i++)
            {
                if (!item.IdTime.Equals(listaCampeoes[i].IdTime))
                {
                    inserir = true;

                }
                else
                {
                    inserir = false;
                    break;
                }
            }
            if (inserir)
            {
                listaCampeoes.Add(item);
            }
        }

    }

    <table class="table table-striped">
        <tr>
            <td></td>
            <th>
                Time
            </th>

            <th>Nº Titulos</th>
        </tr>

        @foreach (var item in listaCampeoes)
        {
            <tr>

                <td>
                    <div class="display-label">
                        <img src="~/Content/images/escudo/@item.EscudoPequeno" height="40">
                    </div>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeTime)
                </td>
                <td>@Html.DisplayFor(modelItem => item.NumeroTitulos)</td>
            </tr>
        }
    </table>


    <br />


    <div class="row-fluid">
        <h2>Campeões por ano</h2>

        <table class="table table-striped">
            <tr>
                <th>
                    Ano Campeonato
                </th>
                <th>
                    Time
                </th>
                <td></td>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => @item.AnoCampeonato)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeTime)
                    </td>
                    <td>
                        <div class="display-label">
                            <img src="~/Content/images/escudo/@item.EscudoPequeno" height="40">
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/Classificacao.cshtml
@model IEnumerable<Campeonato.Dominio.Classificacao>

    @{
        ViewBag.Title = "Futebol Lima Duarte";
    }


    <h2>Classificacao</h2>

    <div class="row-fluid">

        <table class="table table-striped">
          
                <tr>
                    <th style="text-align:left">
                        <b>Posição</b>
                    </th>
                    <th style="text-align:left">
                        Time
                    </th>

                    <th>
                        Pontos
                    </th>
                    <th class="hidden-xs">
                        Jogos
                    </th>
                    <th class="hidden-xs">
                        Vitórias
                    </th>
                    <th class="hidden-xs">
                        Derrotas
                    </th>
                    <th class="hidden-xs">
                        Empates
                    </th>
                    <th class="hidden-xs">
                        Gols Pro
                    </th>
                    <th class="hidden-xs">
                        Gols Contra
                    </th>
                    <th class="hidden-xs">
                        Saldo Gols
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align:left">
                            @Html.DisplayFor(modelItem => item.Posicao)º
                        </td>
                        <td style="text-align:left">
                            @Html.DisplayFor(modelItem => item.NomeTime)
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.Pontos)
                        </th>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.Jogos)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.Vitoria)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.Derrota)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.Empate)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.GolPro)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.GolContra)
                        </td>
                        <td class="hidden-xs">
                            @Html.DisplayFor(modelItem => item.SaldoGol)
                        </td>
                    </tr>
                }
        </table><p>
            <!--<a href="https://www.facebook.com/groups/602547396436819/#" target="_blank"><img src="~/Content/images/facebook.png" border="0" /></a>-->
        </p>

    </div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/Detalhes.cshtml
@model Campeonato.Dominio.Campeonatos

@{
    ViewBag.Title = "Futebol Lima Duarte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <h2>Detalhes</h2>

    <fieldset>
        <legend>Campeonatos</legend>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Nome)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Nome)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.DataInicio)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.DataInicio)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.QuantidadeTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.QuantidadeTime)
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
        @Html.ActionLink("Voltar", "Index")
    </p>
</div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/Editar.cshtml
@model Campeonato.Dominio.Campeonatos

@{
    ViewBag.Title = "Futebol Lima Duarte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <h2>Editar</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Campeonatos</legend>

            @Html.HiddenFor(model => model.Id)

            <div class="editor-label">
                @Html.LabelFor(model => model.Nome)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Nome)
                @Html.ValidationMessageFor(model => model.Nome)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.DataInicio)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DataInicio)
                @Html.ValidationMessageFor(model => model.DataInicio)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.QuantidadeTime)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.QuantidadeTime)
                @Html.ValidationMessageFor(model => model.QuantidadeTime)
            </div>

            <p>
                <input class="btn btn-primary btn-large"  type="submit" value="Save" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/EnviarMensagemGoogle.cshtml
@model GerenciadorCampeonato.Models.EnviarMensagemGoogle

@{
    ViewBag.Title = "EnviarMensagemGoogle";
}

<h2>Envia rMensagem Google</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("EnviarMensagemGoogleCloud", "Campeonato", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Enviar mensagem para todos od dispositivos.</h4>
                <hr />
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.Message, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Message, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.TickerText, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.TickerText, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ContentTitle, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.ContentTitle, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Enviar Mensagem" class="btn btn-default" />
                    </div>
                </div>

            }
        </section>
    </div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/Excluir.cshtml
@model Campeonato.Dominio.Campeonatos

@{
    ViewBag.Title = "Futebol Lima Duarte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <h2>Excluir</h2>

    <h3>Are you sure you want to delete this?</h3>
    <fieldset>
        <legend>Campeonatos</legend>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Nome)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Nome)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.DataInicio)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.DataInicio)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.QuantidadeTime)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.QuantidadeTime)
        </div>
    </fieldset>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            <input class="btn btn-primary btn-large" type="submit" value="Delete" /> |
            @Html.ActionLink("Voltar", "Index")
        </p>
    }
</div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/Index.cshtml
@model IEnumerable<Campeonato.Dominio.Campeonatos>

    @{
        ViewBag.Title = "Futebol Lima Duarte";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <div class="row-fluid">
       
        <p>
            <!-- COMENTADO ATE ARRUMAR AUTENTICACAO
                //@Html.ActionLink("Cadastrar Campeonato", "Cadastrar")
                -->
        </p>

        <table class="table table-striped">
            <tr>
                <th>
                    Campeonato
                </th>
                <th>
                    Inicio
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(@item.Nome, "TimesPorCampeonato", new { idCampeonato = item.Id })
                    </td>
                    <td class="hidden-xs">
                        @Html.DisplayFor(modelItem => item.DataInicio)
                    </td>
                    <td>
                        <!--
                            COMENTADO ATE ARRUMAR AUTENTICACAO
                            @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                        @Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id }) |
                        @Html.ActionLink("Excluir", "Excluir", new { id = item.Id })  |
                        @Html.ActionLink("Selecionar Times", "SelecionarTimes", new { id = item.Id })
                        -->
                        @Html.ActionLink("Classificação", "Classificacao", new { id = item.Id }) |
                        @Html.ActionLink("Tabela", "Tabela", new { id = item.Id }) |
                    </td>
                </tr>
            }
            <tr>
                <td>@Html.ActionLink("Campeões por Ano 1ª Divisão", "CampeoesPorCampeonato", new { id = "1" }) </td>
                <td> </td>
                <td></td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Campeões por Ano 2ª Divisão", "CampeoesPorCampeonato", new { id = "2" }) </td>
                <td> </td>
                <td></td>
            </tr>
        </table>
    </div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/SelecionarTimes.cshtml
@model  Campeonato.Dominio.TimeCampeonato

@{
    ViewBag.Title = "Futebol Lima Duarte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <h2>Selecione os times</h2>

    @using (Html.BeginForm("SelecionarTimes", "Campeonato"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <input type="text" name="idCampeonato" hidden="hidden" value="@Model.IdCampeonato">
        <table class="table table-bordered">
            <tr>
                <td>
                    ID Time
                </td>

                <td>
                    Time
                </td>
                <td>
                    Selecionado
                </td>

            </tr>
            @foreach (var item in Model.Times)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(model => item.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(model => item.Nome)
                    </td>

                    <td>
                        @Html.CheckBox("" + item.Id)
                    
                    </td>

                </tr>
            }
        </table>
        <input class="btn btn-primary btn-large" type="submit" value="SelecionarTimes" />
    }

    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>

FutebolLimaDuarte/GerenciadorCampeonato/Areas/Admin/Views/Campeonato/TimesPorCampeonato.cshtml
@model  Campeonato.Dominio.TimeCampeonato

@{
    ViewBag.Title = "Futebol Lima Duarte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <h2>Times participantes</h2>

    @using (Html.BeginForm("SelecionarTimes", "Campeonato"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <input type="hidden" name="idCampeonato" value="@Model.IdCampeonato">
        <table class="table table-striped">
            <tr>
                <td></td>
                <td>
                    Time
                </td>
            </tr>
            @foreach (var item in Model.Times)
            {
                <tr>
                    <td>
                        <div class="display-label">
                            <img src="~/Content/images/escudo/@item.EscudoPequeno" height="40">
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Nome)
                    </td>
                </tr>
            }
        </table>
    }
    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>