FutebolLimaDuarte/GerenciadorCampeonato/Controllers/ArtilhariaWebController.cs
using GerenciadorCampeonato.Controllers.Abstratos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Campeonato.Business.Logics;
using Campeonato.Dominio;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Collections;
using GerenciadorCampeonato.Controllers.Abstratos;

namespace GerenciadorCampeonato.Controllers
{
    public class ArtilhariaWebController : BaseController
    {
        ArtilhariaBusiness artilhariaBusiness = new ArtilhariaBusiness();
        JogadorBusiness jogadorBusiness = new JogadorBusiness();
        TimeBusiness timeBusiness = new TimeBusiness();
        CampeonatoBusiness campeonatoBusiness = new CampeonatoBusiness();


        public ArtilhariaWebController()
        {
            List<Jogador_Web> listaJogador = jogadorBusiness.ObterJogador();
            List<Artilharia_Web> listaArtilharia = artilhariaBusiness.ObterArtilharia();
           // listaJogador = listaJogador.Where(a => a.Id != listaArtilharia.Where(b => b.Id_Jogador == a.Id).First().Id_Jogador).ToList();

            Jogador_Web valorPrincipalJogador = new Jogador_Web { Id = 0, Nome = "Selecione um valor" };
            listaJogador.Add(valorPrincipalJogador);
            var jogadores = listaJogador.Select(i => new { id = i.Id, descricao = i.Nome });
            ViewData["JogadorControle_Data"] = new SelectList(jogadores, "id", "descricao");



            List<Time_Web> listaTime = timeBusiness.ObterTime();
            Time_Web valorPrincipalTime = new Time_Web { Id = 0, Nome = "Selecione um valor" };
            listaTime.Add(valorPrincipalTime);
            var times = listaTime.Select(i => new { id = i.Id, descricao = i.Nome });
            ViewData["TimeControle_Data"] = new SelectList(times, "id", "descricao");

            List<Campeonato_Web> listaCampeonato = campeonatoBusiness.ObterCampeonato();
            Campeonato_Web valorPrincipal = new Campeonato_Web { Id = 0, Nome = "Selecione um valor" };
            listaCampeonato.Add(valorPrincipal);
            var campeonatos = listaCampeonato.Select(i => new { id = i.Id, descricao = i.Nome });
            ViewData["CampeonatoControle_Data"] = new SelectList(campeonatos, "id", "descricao");
        }

        public ActionResult Consultar()
        {
            if (!string.IsNullOrEmpty(User.Identity.Name))
                return View("~/Views/Artilharia/Index.cshtml");
            else
                return View("~/Views/AdminHome/Login.cshtml");            
        }

        public ActionResult Ler([DataSourceRequest] DataSourceRequest request)
        {
            List<Artilharia_Web> artilharia_Web = new List<Artilharia_Web>();

            try
            {
                artilharia_Web = artilhariaBusiness.ObterArtilharia();

                return Json(artilharia_Web.ToList().ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(artilharia_Web.ToList().ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Inserir([DataSourceRequest] DataSourceRequest request, Artilharia_Web item)
        {
            try
            {
                List<Jogador_Web> jogadores = jogadorBusiness.ObterJogador();
                
                item.Id_Time = jogadores.Where(a => a.Id == item.Id_Jogador).FirstOrDefault().Id_Time;
                item.Id_Campeonato = 1;
                artilhariaBusiness.InserirArtilharia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Atualizar([DataSourceRequest] DataSourceRequest request, Artilharia_Web item)
        {
            try
            {
                artilhariaBusiness.AtualizaArtilharia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }

        }

        public ActionResult Apagar([DataSourceRequest] DataSourceRequest request, Artilharia_Web item)
        {
            try
            {
                artilhariaBusiness.RemoveArtilharia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        //public FileResult Exportar([DataSourceRequest] DataSourceRequest request, string arquivo, string colunas)
        //{
        //    var lista = jogadorBusiness.ObterEquipe();
        //    return base.Exportar(request, lista != null ? (IEnumerable)lista : null, arquivo, colunas);
        //}

    }
}

FutebolLimaDuarte/GerenciadorCampeonato/Controllers/JogadorWebController.cs
using GerenciadorCampeonato.Controllers.Abstratos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Campeonato.Business.Logics;
using Campeonato.Dominio;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Collections;
using GerenciadorCampeonato.Controllers.Abstratos;

namespace GerenciadorCampeonato.Controllers
{
    public class JogadorWebController : BaseController
    {

        JogadorBusiness jogadorBusiness = new JogadorBusiness();
        TimeBusiness timeBusiness = new TimeBusiness();
        CampeonatoBusiness campeonatoBusiness = new CampeonatoBusiness();
        ArtilhariaBusiness artilhariaBusiness = new ArtilhariaBusiness();


        public JogadorWebController()
        {
            List<Time_Web> listaTime = timeBusiness.ObterTime();
            Time_Web valorPrincipalTime = new Time_Web { Id = 0, Nome = "Selecione um valor" };
            listaTime.Add(valorPrincipalTime);
            var times = listaTime.Select(i => new { id = i.Id, descricao = i.Nome });
            ViewData["TimeControle_Data"] = new SelectList(times, "id", "descricao");

            List<Campeonato_Web> listaCampeonato = campeonatoBusiness.ObterCampeonato();
            Campeonato_Web valorPrincipal = new Campeonato_Web { Id = 0, Nome = "Selecione um valor" };
            listaCampeonato.Add(valorPrincipal);

            var campeonatos = listaCampeonato.Select(i => new { id = i.Id, descricao = i.Nome });

            ViewData["CampeonatoControle_Data"] = new SelectList(campeonatos, "id", "descricao");
        }

        public ActionResult Consultar()
        {            
            if (!string.IsNullOrEmpty(User.Identity.Name))
                return View("~/Views/Jogador/Index.cshtml");
            else
                return View("~/Views/AdminHome/Login.cshtml");            
        }

        public ActionResult Ler([DataSourceRequest] DataSourceRequest request)
        {
            List<Jogador_Web> jogador_Web = new List<Jogador_Web>();

            try
            {
                jogador_Web = jogadorBusiness.ObterJogador();

                return Json(jogador_Web.ToList().ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(jogador_Web.ToList().ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Inserir([DataSourceRequest] DataSourceRequest request, Jogador_Web item)
        {
            try
            {
                jogadorBusiness.InserirJogador(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Atualizar([DataSourceRequest] DataSourceRequest request, Jogador_Web item)
        {
            try
            {
                jogadorBusiness.AtualizaJogador(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }

        }

        public ActionResult Apagar([DataSourceRequest] DataSourceRequest request, Jogador_Web item)
        {
            try
            {
                jogadorBusiness.RemoveJogador(item);

                jogadorBusiness.RemoveArtilharia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        //public FileResult Exportar([DataSourceRequest] DataSourceRequest request, string arquivo, string colunas)
        //{
        //    var lista = jogadorBusiness.ObterEquipe();
        //    return base.Exportar(request, lista != null ? (IEnumerable)lista : null, arquivo, colunas);
        //}

    }
}

FutebolLimaDuarte/GerenciadorCampeonato/Controllers/NoticiaWebController.cs
using GerenciadorCampeonato.Controllers.Abstratos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Campeonato.Business.Logics;
using Campeonato.Dominio;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Collections;
using System.IO;
using System.Drawing;

namespace GerenciadorCampeonato.Controllers
{
    public class NoticiaWebController : BaseController
    {

        NoticiaBusiness noticiaBusiness = new NoticiaBusiness();

        public ActionResult Consultar()
        {
            if (!string.IsNullOrEmpty(User.Identity.Name))
                return View("~/Views/Noticia/Index.cshtml");
            else
                return View("~/Views/AdminHome/Login.cshtml");              
        }

        public ActionResult Ler([DataSourceRequest] DataSourceRequest request)
        {
            List<Noticia_Web> noticia_Web = new List<Noticia_Web>();

            try
            {
                noticia_Web = noticiaBusiness.ObterNoticia();

                return Json(noticia_Web.ToList().ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(noticia_Web.ToList().ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Inserir([DataSourceRequest] DataSourceRequest request, Noticia_Web item)
        {
            try
            {
                noticiaBusiness.InserirNoticia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Atualizar([DataSourceRequest] DataSourceRequest request, Noticia_Web item)
        {
            try
            {
                noticiaBusiness.AtualizaNoticia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }

        }

        public ActionResult Apagar([DataSourceRequest] DataSourceRequest request, Noticia_Web item)
        {
            try
            {
                noticiaBusiness.RemoveNoticia(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }
    }
}

FutebolLimaDuarte/GerenciadorCampeonato/Controllers/TimeWebController.cs
using GerenciadorCampeonato.Controllers.Abstratos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Campeonato.Business.Logics;
using Campeonato.Dominio;
using System.Web.Mvc;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Collections;
using System.IO;
using System.Drawing;

namespace GerenciadorCampeonato.Controllers
{
    public class TimeWebController : BaseController
    {

        TimeBusiness timeBusiness = new TimeBusiness();

        public ActionResult Consultar()
        {
            if (!string.IsNullOrEmpty(User.Identity.Name))
                return View("~/Views/Time/Index.cshtml");
            else
                return View("~/Views/AdminHome/Login.cshtml");              
        }

        public ActionResult AnexarEscudo(string id)
        {
            if (!string.IsNullOrEmpty(User.Identity.Name))
                return View("~/Views/Time/AnexarEscudo.cshtml");
            else
                return View("~/Views/AdminHome/Login.cshtml");
        }

        public ActionResult Ler([DataSourceRequest] DataSourceRequest request)
        {
            List<Time_Web> time_Web = new List<Time_Web>();

            try
            {
                time_Web = timeBusiness.ObterTime();

                return Json(time_Web.ToList().ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(time_Web.ToList().ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Inserir([DataSourceRequest] DataSourceRequest request, Time_Web item)
        {
            try
            {
                timeBusiness.InserirTime(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Atualizar([DataSourceRequest] DataSourceRequest request, Time_Web item)
        {
            try
            {
                timeBusiness.AtualizaTime(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }

        }

        public ActionResult Apagar([DataSourceRequest] DataSourceRequest request, Time_Web item)
        {
            try
            {
                timeBusiness.RemoveTime(item);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                return Json(new[] { item }.ToDataSourceResult(request, ModelState));
            }
        }

        public ActionResult Submit(string files)
        {
            byte[] byteArrayIn = System.Text.Encoding.ASCII.GetBytes(files);
            MemoryStream ms = new MemoryStream(byteArrayIn);
            Image returnImage = Image.FromStream(ms);
            if (!Directory.Exists(AppDomain.CurrentDomain.BaseDirectory + "/imagens"))
            {
                Directory.CreateDirectory(AppDomain.CurrentDomain.BaseDirectory + "/imagens");
            }
            returnImage.Save(AppDomain.CurrentDomain.BaseDirectory + "/imagens/" + files);
            return null;
        }

        //public FileResult Exportar([DataSourceRequest] DataSourceRequest request, string arquivo, string colunas)
        //{
        //    var lista = equipeBusiness.ObterEquipe();
        //    return base.Exportar(request, lista != null ? (IEnumerable)lista : null, arquivo, colunas);
        //}

    }
}

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/NaoEncontrado.cshtml
@{
    ViewBag.Title = "Registro não encontrado";
}

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Breadcrumb.cshtml
@if(ViewBag.Breadcrumbs != null && (ViewBag.Breadcrumbs as List<KeyValuePair<string, string>>).Count > 0)
{ 
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="/">Inicial</a>
            <i class="fa fa-angle-right"></i>
        </li>
        @{
            var breadCrumbs = ViewBag.Breadcrumbs as List<KeyValuePair<string, string>>;
        
            for (int i = 0; i < breadCrumbs.Count; i++)
            {
                <li>
                    <a href="@breadCrumbs[i].Key">@breadCrumbs[i].Value</a>
                                
                    @if (i < (breadCrumbs.Count - 1))
                    {                        
                        <i class="fa fa-angle-right"></i>
                    }
                                
                </li>  
            }           
        }    
    </ul>
}

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_ConfigurationMenu.cshtml
@{
    /*
    <div class="theme-panel hidden-xs hidden-sm">
        <div class="toggler">
            <i class="fa fa-gear"></i>
        </div>
        <div class="theme-options" style="min-width: 250px">
            <div class="theme-option theme-colors clearfix">
                <span style="font-weight: 600">Parametrização</span>
            </div>
            <div class="theme-option">
                <span style="font-weight: 600; margin-bottom: .4em">Configurações</span>
                <a href="/TipoRequisicaoAcidente/">Tipo de Requisição do Acidente</a>
                <a href="/SessaoRequisicaoAcidente/">Seção de Requisição do Acidente</a>
                <a href="#">Grupo de Requisição do Acidente</a>
                <a href="#">Domínio Valor de Requisição do Acidente</a>
            </div>
            <div class="theme-option">
                <span style="font-weight: 600; margin-bottom: .4em">Cadastros&nbsp;Básicos</span>
                <a href="/TipoGravidadeAcidente">Tipo de Gravidade de Acidente</a>
                <a href="/TipoElementoAcidentado">Tipo de Elemento Acidentado</a>
                <a href="/TipoCausaAcidente">Tipo Causa Acidente</a>
                <a href="/TipoAcidente">Tipo do Acidente</a>
                <a href="/TipoItemApuracao">Tipos de Item para Apuração</a>
                <a href="/StatusSituacaoIndenizacao">Situação da Indenização</a>
                <a href="/MotivoIncidente">Motivos de Incidentes</a>
                <a href="#">Meta de Segurança e Risco</a>
            </div>
        </div>
    </div>

    <style>
        .theme-option a {
            display: block;
            padding: .4em 0 .4em .8em;
            color: #333;
            text-decoration: none;
        }

        .theme-option a:hover {
            background-color: #e1e1e1;
        }
    </style>
     */
}

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Head.cshtml
<link rel="stylesheet" type="text/css" href="~/Content/ComponentesPersonalizados/autoCompletePatioFerroviario.css" />
<link rel="stylesheet" type="text/css" href="~/Content/ComponentesPersonalizados/autoCompleteTerminalFerroviario.css" />
<link rel="stylesheet" type="text/css" href="~/Content/ComponentesPersonalizados/autoCompleteTrem.css" />
<link rel="stylesheet" type="text/css" href="~/Content/ComponentesPersonalizados/autoCompleteVeiculoFerroviario.css" />

<link rel="stylesheet" type="text/css" href="~/Content/timeline.css" />

@*<script src="@Url.Content("~/Scripts/portal.js")"></script>*@

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <link rel="shortcut icon" href="~/Content/images/icons/Gol.png">
    <meta name="MobileOptimized" content="320">

    <link type="text/css" rel="stylesheet" href="~/Content/core/css/font-awesome.min.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/style-conquer.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/style.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/style-responsive.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/light.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/mission-gothic.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/core/css/core.css" />

    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="~/Content/kendo/2014.2.716/kendo.common.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/kendo/2014.2.716/kendo.dataviz.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/kendo/2014.2.716/kendo.bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/kendo/2014.2.716/kendo.dataviz.bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />

    <script src="~/Content/core/js/respond.min.js"></script>
    <script src="~/Content/core/js/excanvas.min.js"></script>

    <script src="~/Scripts/kendo/2014.2.716/jquery.min.js"></script>
    <script src="~/Scripts/kendo/2014.2.716/kendo.all.min.js"></script>
    <script src="~/Scripts/kendo/2014.2.716/kendo.aspnetmvc.min.js"></script>
    <script src="~/Scripts/kendo.modernizr.custom.js"></script>
    <script src="~/Scripts/kendo/2014.2.716/cultures/kendo.culture.pt-BR.min.js"></script>

    <script src="~/Content/core/js/bootstrap.min.js"></script>
    <script src="~/Content/core/js/jquery.slimscroll.min.js"></script>
    <script src="~/Content/core/js/jquery.cokie.min.js"></script>
    <script src="~/Content/core/js/app.js"></script>

    <script src="@Url.Content("~/Scripts/portal.js")"></script>
    <script>kendo.culture("pt-BR");</script>

    @try
    {
        @Html.Partial("_Head")
    }
    catch { }

</head>
<body class="page-header-fixed">
    <div class="header navbar navbar-inverse navbar-fixed-top">
        <div class="header-inner">
            <a class="navbar-brand" href="/">
                <img src="~/Content/core/img/copaalterosa_mini.png" alt="logo" />
                <span class="app-title">
                    @try
                    {
                        @Html.Partial("_Title")
                    }
                    catch
                    {
                        @:Sistema Copa Alterosa Sub-20
                    }
                </span>
            </a>
            <a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <img src="~/Content/core/img/menu-toggler.png" alt="" />
            </a>
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style="padding-top: 12px">
                        <span class="glyphicon glyphicon-user" style="margin-right: 5px"></span>
                        <span class="username">@User.Identity.Name</span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/AdminHome/Logoff"><i class="fa fa-key"></i> Sair</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <br />
    <div class="clearfix"></div>
    <div class="page-container">
        <div class="page-sidebar-wrapper">
            <div class="page-sidebar-wrapper">
                <div class="page-sidebar navbar-collapse collapse">
                    <ul class="page-sidebar-menu">
                        <li class="sidebar-toggler-wrapper">
                            <div class="sidebar-toggler"></div>
                            <div class="clearfix"></div>
                        </li>
                        @try
                        {
                            @Html.Partial("_Menu")
                        }
                        catch (Exception ex)
                        {
                            <li class="start">
                                @Conquer.MenuTitle("Sistema Copa Alterosa Sub-20", "fa-home", Url.Action("Index", "AdminHome"))
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="page-content-wrapper">
            <div class="page-content-wrapper">
                <div class="page-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="page-title">@ViewBag.Title &nbsp; <span style="font-size:16px;">@ViewBag.TitleComplement</span></div>
                            @try
                            {
                                @Html.Partial("_Breadcrumb")
                            }
                            catch
                            {
                                <ul class="page-breadcrumb breadcrumb">
                                    <li>
                                        <i class="fa fa-home"></i>
                                        <a href="/">Inicial</a>
                                        <i class="fa fa-angle-right"></i>
                                    </li>
                                    <li>
                                        <a href="#">@ViewBag.Title</a>
                                    </li>
                                </ul>
                            }
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="footer-inner footer-copyright">Copa Alterosa</div>
        <span class="label label-info label-version">
            @try
            {
                @Html.Partial("_Version")
            }
            catch
            {
                @:1.0.0
            }
        </span>
        <div class="footer-tools">
            <span class="go-top">
                <i class="fa fa-angle-up"></i>
            </span>
        </div>
    </div>
    <script>

        $(function () {
            App.init();
            var action = $(".page-sidebar-menu a[href='" + window.location.pathname + "']");
            $(action).closest("li").addClass("active");
            $(action).closest(".sub-menu").css("display", "block");
            $(action).closest(".page-sidebar-menu > li").addClass("open active");
        });

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Menu.cshtml
<li class="start">
    @Conquer.MenuTitle("Menu", "fa-home", Url.Action("Index", "AdminHome"))
</li>
@if (User.Identity.Name.ToString() == "joaocelson@gmail.com")
{
    <li style="display: block">
        @Conquer.MenuTitle("Times", "fa-tags", Url.Action("Consultar", "TimeWeb"))
    </li>

    <li style="display: block">
        @Conquer.MenuTitle("Campeonato", "fa-life-ring", Url.Action("Consultar", "CampeonatoWeb"))
    </li>
}
<li style="display: block">
    @Conquer.MenuTitle("Jogadores", "fa-user", Url.Action("Consultar", "JogadorWeb"))
</li>
<li style="display: block">
    @Conquer.MenuTitle("Partidas", "fa-flag", Url.Action("Consultar", "PartidaWeb"))
</li>
<li style="display: block">
    @Conquer.MenuTitle("Resultado Partidas", "fa-child", Url.Action("Consultar", "ResultadoPartidaWeb"))
</li>
<li style="display: block">
    @Conquer.MenuTitle("Classificação", "fa-trophy", Url.Action("Classificacao", "CampeonatoWeb"))
</li>
<li style="display: block">
    @Conquer.MenuTitle("Artilharia", "fa-star", Url.Action("Consultar", "ArtilhariaWeb"))
</li>
<li style="display: block">
    @Conquer.MenuTitle("Notícias", "fa-file-text-o", Url.Action("Consultar", "NoticiaWeb"))
</li>
<li style="display: block">
    @Conquer.MenuTitle("Enviar Notificação App", "fa-envelope", Url.Action("EnviarMensagem", "Home"))
</li>

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Search.cshtml
@using (Html.BeginForm("Consultar", "BuscaGenerica", FormMethod.Post, new
{
    @class = "search-form search-form-header",
    id = "formPesquisa",
    onsubmit = "return false;"
}))
{
    <div class="input-icon right">
        <i class="fa fa-search" id="iconePesquisa"></i>
        <input type="text" class="form-control input-medium input-sm" name="txtPesquisa" id="txtPesquisa" placeholder="Pesquisar...">        
    </div>
}
<script>
    $("#txtPesquisa").keyup(function (event) {
        if (event.keyCode == 13) {
            submitSearchForm();
        }
    });

    $("#iconePesquisa").click(function (e) {
        submitSearchForm();
    });

    function submitSearchForm() {
        if ($("#txtPesquisa").val() != null && $("#txtPesquisa").val() != '')
            document.forms["formPesquisa"].submit();

    }
</script>

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Title.cshtml
Copa Alterosa Sub-20

FutebolLimaDuarte/GerenciadorCampeonato/Views/Shared/_Version.cshtml
1.0.0.0